### PR TITLE
Fix package-lock.json conflicts

### PR DESCRIPTION
**Pull request by rhian-cs**
## Proposed Changes

Run `npm install` to update lockfile and fix up changes

## Screenshots

Not applicable.

## Checklist

- [x] I have run `npm run lint:fix` and `npm run format` before opening this PR.
- [x] I have ensured that running `npm run lint` shows no more errors

### CODE REVIEW

**Review by afpaiva — APPROVED** [review]
I didn't understand the purpose, can you give me more details?
Totally trust you, so for me it's approved. ;)

**Comment by rhian-cs** [comment]
> I didn't understand the purpose, can you give me more details? Totally trust you, so for me it's approved. ;)

The current `package-lock.json` had some conflicts left over from another merge, you can see this by looking at the line: https://github.com/tai-II-plataforma-educacional/web-frontend/pull/11/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519L6-L7

Also, when I ran `npm install` it updated the lockfile version from 1 to 2, which is the one being used by the latest `npm` version.

**Comment by afpaiva** [comment]
> > I didn't understand the purpose, can you give me more details? Totally trust you, so for me it's approved. ;)
> 
> The current `package-lock.json` had some conflicts left over from another merge, you can see this by looking at the line: https://github.com/tai-II-plataforma-educacional/web-frontend/pull/11/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519L6-L7
> 
> Also, when I ran `npm install` it updated the lockfile version from 1 to 2, which is the one being used by the latest `npm` version.

What I use to do in this case is delete this file, commit, push and then run `npm install again`.
This avoid conflicts. But I'm not sure if this is a good practice.

**Comment by rhian-cs** [comment]
> What I use to do in this case is delete this file, commit, push and then run `npm install again`. This avoid conflicts. But I'm not sure if this is a good practice.

@afpaiva This shouldn't be necessary, as the lockfile should always be kept up to date.

Next time we get conflicts in the lockfile, let's resolve the conflicts in the editor and rerun `npm install` before commiting the changes.

By the way, you should update your `npm` version with `npm install -g npm` so that it can use the new lockfile version with ease.

**Pull request merged**
